version: '2'
networks:
  my-network-name:
    name: ${NETWORK_NAME}
    driver: bridge
services:
  zookeeper-1:
    container_name: ${ZOOKEEEPER_SERVICE_NAME_FIRST}
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - my-network-name
  zookeeper-2:
    container_name: ${ZOOKEEEPER_SERVICE_NAME_SECOND}
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 32181:2181
    networks:
      - my-network-name

  kafka_1:
    container_name: ${KAFKA_SERVICE_NAME_FIRST}
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 29092:29092
    # entrypoint:
    #   - "sh"
    #   - "-c"
    #   - "echo -n \"Wait until Zookeeper is fully initiliazed...\"; \
    #      ping -c 1 -w 5 zookeeper > /dev/null 2>&1; \
    #      while [ \"$$(echo ruok | nc zookeeper 2181)\" != \"imok\" ]; do \
    #        echo -n \"...\"; \
    #        sleep 1; \
    #      done; \
    #      echo \"...done\"; \
    #      /etc/confluent/docker/run"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - my-network-name
  kafka-2:
    container_name: ${KAFKA_SERVICE_NAME_SECOND}
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 39092:39092
    # entrypoint:
    #   - "sh"
    #   - "-c"
    #   - "echo -n \"Wait until Zookeeper is fully initiliazed...\"; \
    #      ping -c 1 -w 5 zookeeper > /dev/null 2>&1; \
    #      while [ \"$$(echo ruok | nc zookeeper 2181)\" != \"imok\" ]; do \
    #        echo -n \"...\"; \
    #        sleep 1; \
    #      done; \
    #      echo \"...done\"; \
    #      /etc/confluent/docker/run"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - my-network-name
