# include help.mk

# tell Make the following targets are not files, but targets within Makefile
.PHONY: env env-stop
.DEFAULT_GOAL := help

NETWORK_NAME = development_network
ZOOKEEEPER_SERVICE_NAME_FIRST = zookeeper_server_1
ZOOKEEEPER_SERVICE_NAME_SECOND = zookeeper_server_2
KAFKA_SERVICE_NAME_FIRST = kafka_server_1
KAFKA_SERVICE_NAME_SECOND = kafka_server_2
KAF_DROP=kaf_drop

env: ##@environment Create network, run kafka and zookeeper services.
	NETWORK_NAME=${NETWORK_NAME} \
	ZOOKEEEPER_SERVICE_NAME_FIRST=$(ZOOKEEEPER_SERVICE_NAME_FIRST) \
	ZOOKEEEPER_SERVICE_NAME_SECOND=$(ZOOKEEEPER_SERVICE_NAME_SECOND) \
	KAFKA_SERVICE_NAME_FIRST=${KAFKA_SERVICE_NAME_FIRST} \
	KAFKA_SERVICE_NAME_SECOND=${KAFKA_SERVICE_NAME_SECOND} \
	KAF_DROP=${KAF_DROP} \
	docker-compose up -d

env-stop: ##@environment Remove kafka and zookeeper containers.
	ZOOKEEEPER_SERVICE_NAME_FIRST=${ZOOKEEEPER_SERVICE_NAME_FIRST} NETWORK_NAME=${NETWORK_NAME} docker-compose kill
	ZOOKEEEPER_SERVICE_NAME_FIRST=${ZOOKEEEPER_SERVICE_NAME_FIRST} NETWORK_NAME=${NETWORK_NAME} docker-compose rm -vf
	ZOOKEEEPER_SERVICE_NAME_SECOND=${ZOOKEEEPER_SERVICE_NAME_SECOND} NETWORK_NAME=${NETWORK_NAME} docker-compose kill
	ZOOKEEEPER_SERVICE_NAME_SECOND=${ZOOKEEEPER_SERVICE_NAME_SECOND} NETWORK_NAME=${NETWORK_NAME} docker-compose rm -vf
	KAFKA_SERVICE_NAME_FIRST=${KAFKA_SERVICE_NAME_FIRST} NETWORK_NAME=${NETWORK_NAME} docker-compose kill
	KAFKA_SERVICE_NAME_FIRST=${KAFKA_SERVICE_NAME_FIRST} NETWORK_NAME=${NETWORK_NAME} docker-compose rm -vf
	KAFKA_SERVICE_NAME_SECOND=${KAFKA_SERVICE_NAME_SECOND} NETWORK_NAME=${NETWORK_NAME} docker-compose kill
	KAFKA_SERVICE_NAME_SECOND=${KAFKA_SERVICE_NAME_SECOND} NETWORK_NAME=${NETWORK_NAME} docker-compose rm -vf
	docker network rm $(NETWORK_NAME)
